Componente inputLatex
OrionAerospace/Interface-Estudos-Frontend pull request #11
Opened 2024-08-02 19:24 UTC by AttJF

2024-08-02 19:40 UTC, gastawny reviewed
Remover arquivos que não são relacionados ao Input

2024-08-02 19:40 UTC, gastawny commented on package.json
>      "react": "^18.2.0",
Remover as dependências que não foram usadas

2024-08-02 19:40 UTC, gastawny commented on src/components/InputLatex/index.tsx
> +  const [value1, setValue1] = useState('')
Melhorar o nome das variáveis e remover o que não foi usado

2024-08-02 19:40 UTC, gastawny commented on src/components/InputLatex/index.tsx
> +  return (
Exportar diretamente o MathInput

2024-08-02 19:40 UTC, gastawny commented on src/utils/convertToLatex.ts
> +export function convertToLatex(input: string): string {
Remover arquivo

2024-08-02 19:40 UTC, gastawny commented on src/components/InputLatex/index.tsx
> +            <MathInput
Ver se esse input aceita className, se aceitar, use a função cn que está dentro da pasta lib

2024-08-07 16:14 UTC, gastawny requested changes
Ver comentários

2025-01-24 00:18 UTC, closed without merging

2025-01-24 00:18 UTC, CaptLuckyTiger commented
Não será implementado