working so far, not complete
OrionAerospace/Interface-Estudos-Frontend pull request #12
Opened 2024-08-05 16:07 UTC by CaptLuckyTiger

2024-08-05 18:05 UTC, gastawny commented on src/components/QuestionForm/styles.module.scss
Usando os componentes prontos, é bem provável que não seja necessário um arquivo separado.

2024-08-05 18:35 UTC, gastawny requested changes
Ver comentários

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/styles.module.scss
Usando os componentes prontos, é bem provável que não seja necessário um arquivo separado.

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/page.tsx
> +interface Question {
Coloque esse tipo dentro da pasta types, faça um tipo base para as questões, podendo criar variações usando o Pick/Omit

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/page.tsx
> +  tags: string[]
crie um tipo para as tags

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/page.tsx
esse componente não será reutilizado, coloque dentro da pasta screens

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/page.tsx
Utilize os componentes dentro de components/ui

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/page.tsx
> +  const [question, setQuestion] = useState<string>('')
usando o react hook form, não será necessário criar tantos estados https://ui.shadcn.com/docs/components/form

Exemplo:
```tsx
"use client"

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"

import { Button } from "@/components/ui/button"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { toast } from "@/components/ui/use-toast"

const FormSchema = z.object({
  username: z.string().min(2, {
    message: "Username must be at least 2 characters.",
  }),
})

export function InputForm() {
  const form = useForm<z.infer<typeof FormSchema>>({
    resolver: zodResolver(FormSchema),
    defaultValues: {
      username: "",
    },
  })

  function onSubmit(data: z.infer<typeof FormSchema>) {
    toast({
      title: "You submitted the following values:",
      description: (
        <pre className="mt-2 w-[340px] rounded-md bg-slate-950 p-4">
          <code className="text-white">{JSON.stringify(data, null, 2)}</code>
        </pre>
      ),
    })
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="w-2/3 space-y-6">
        <FormField
          control={form.control}
          name="username"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Username</FormLabel>
              <FormControl>
                <Input placeholder="shadcn" {...field} />
              </FormControl>
              <FormDescription>
                This is your public display name.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit">Submit</Button>
      </form>
    </Form>
  )
}
```

Para os schemas, existe a pasta zod/schemas

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/page.tsx
> +  const handleSubmit = (event: FormEvent) => {
Faça o mock da requisição, para isso crie um novo service ```QuestionService```. Esse mock será utilizado dentro de handleSubmit.

Quando terminar o resultado da promise, use um [toast](https://ui.shadcn.com/docs/components/toast) para informar o resultado

2024-08-05 18:35 UTC, gastawny commented on src/components/QuestionForm/page.tsx
> +    addQuestion(newQuestion)
Essa função não é necessária.

2024-08-08 23:07 UTC, gastawny requested changes
Ver comentários abertos

2024-08-08 23:07 UTC, gastawny commented on src/screens/QuestionForm/page.tsx
> +        <FormItem>
usar esta estrutura para os campos

```tsx
<FormField
  control={form.control}
  name="username"
  render={({ field }) => (
    <FormItem>
      <FormLabel>Username</FormLabel>
      <FormControl>
        <Input placeholder="shadcn" {...field} />
      </FormControl>
      <FormDescription>
        This is your public display name.
      </FormDescription>
      <FormMessage />
    </FormItem>
  )}
/>
```

2024-08-09 23:21 UTC, CaptLuckyTiger commented on src/app/test/page.tsx
> +  const mockAddQuestion = (newQuestion: Question) => {
Tava usando para checar no console os testes, não vai precisar mesmo

2024-08-10 15:42 UTC, CaptLuckyTiger commented on src/screens/QuestionForm/page.tsx
> +        <FormItem>
![Sem título](https://github.com/user-attachments/assets/84762e46-27a6-40a1-bc3d-5ebf023fdddc)

2024-08-12 15:18 UTC, gastawny requested changes
Ver comentários abertos

2024-08-12 15:18 UTC, gastawny commented on src/screens/QuestionForm/page.tsx
> +        <FormItem>
As tags serão um array que virá pronto do back (faça o mock da requisição), mudar esse campo para um multi-select.

O componente Select não dá esse suporte, mas existem variações que usam como base o shadcn.

Acredito que basta copiar o código de alguma variação e criar um novo componente chamado MultiSelect, dentro de components/ui

2024-10-02 11:59 UTC, CaptLuckyTiger commented on package.json
> +    "react-toastify": "^10.0.5",
done

2024-10-02 15:59 UTC, gastawny commented on src/components/ui/multiselect.tsx
> +                        Clear
Traduzir

2024-10-02 15:59 UTC, gastawny commented on src/components/ui/multiselect.tsx
> +                    Close
Traduzir

2024-10-02 15:59 UTC, gastawny commented on src/components/ui/multiselect.tsx
> +                  <span>(Select All)</span>
Traduzir

2024-10-02 16:00 UTC, gastawny commented on src/components/ui/multiselect.tsx
> +              <CommandEmpty>No results found.</CommandEmpty>
Traduzir

2024-10-02 16:00 UTC, gastawny commented on src/components/ui/multiselect.tsx
> +      placeholder = 'Select options',
traduzir

2024-10-07 11:20 UTC, gastawny approved these changes

2024-10-07 11:20 UTC, merged