Loginout
OrionAerospace/Interface-Estudos-Frontend pull request #7
Opened 2024-07-01 14:34 UTC by CaptLuckyTiger

2024-07-01 15:12 UTC, gastawny commented on package.json
> +    "react-router-dom": "^6.24.0",
Por que adicionou esta linha?

2024-07-01 15:15 UTC, gastawny commented on src/services/RemoveCookies.ts
> +export function handleRemoveCookie() {
Colocar essa função dentro de ```UserService``` e mudar o nome para ```logout```

2024-07-01 15:17 UTC, gastawny commented on src/services/RemoveCookies.ts
> +  window.location.href = '/login'
usar [useRouter](https://nextjs.org/docs/app/api-reference/functions/use-router) se for client component, e para server components use o  [redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)

2024-07-01 15:18 UTC, CaptLuckyTiger commented on package.json
> +    "react-router-dom": "^6.24.0",
Ah isso eu tinha feito, só por teste mesmo, tinha feito de uma forma errada a remoção de cookies acabei nem usando ele.

2024-07-01 15:19 UTC, gastawny commented on src/app/(home)/page.tsx
> +        <Link href="/login"> Entrar</Link>
espaço no html " Entrar"

2024-07-01 15:21 UTC, gastawny commented on src/app/disciplinas/layout.tsx
> +import { handleRemoveCookie } from '@/services/RemoveCookies'
importar o ```useUser``` e utilizar a funcao ```logout``` que será criada

2024-07-01 15:21 UTC, gastawny commented on src/components/Button/LogoutButton.tsx
> +import React from 'react'
Remover este arquivo

2024-07-01 15:24 UTC, gastawny requested changes
Veja os comentários e o motivo de não ter passado na 'Continuous Integration with GitHub Actions / linter'.

2024-07-01 23:55 UTC, CaptLuckyTiger commented
All issues fixed.

2024-07-02 23:04 UTC, gastawny commented on src/screens/Button/LogoutButton.tsx
> +const RemoveCookieButton = () => {
usar function

2024-07-02 23:05 UTC, gastawny commented on src/screens/Button/LogoutButton.tsx
> +  const handleLogout = () => {
usar function

2024-07-02 23:07 UTC, gastawny commented on src/screens/Button/LogoutButton.tsx
> +      type="button"
tirar esse ```type``` e deixar apenas ```onClick={handleLogout}```

2024-07-02 23:09 UTC, gastawny commented on src/app/disciplinas/layout.tsx
> +              {/* <li>Perfil</li> */}
- Retirar o cometário
- Colocar a tag ```li``` em volta do ```Link``` e do ```RemoveCookieButton```

2024-07-02 23:10 UTC, gastawny commented on src/screens/Button/LogoutButton.tsx
> +export default RemoveCookieButton
nao usar ```export default```, isso ajuda no autocomplete

2024-07-02 23:12 UTC, gastawny requested changes
Ver comentários

2024-07-02 23:34 UTC, CaptLuckyTiger commented
Corrigido

2024-07-02 23:42 UTC, gastawny approved these changes

2024-07-02 23:43 UTC, merged